spring:
  profiles:
    active: ${mvn.profile.active}
  application:
    name: demo-application
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://223.247.141.69:3306/springboot_demo?characterEncoding=UTF-8
    username: springboot_demo
    password: springboot_demo



mybatis:
  mapper-locations: classpath*:mapper/*.xml



web:
  log:
    http:
      - path: /demo
        methods: GET
        log:
          disable-req: true
          disable-resp: true
      - path: /demo/form
        methods: POST
        log:
          disable-req-body: true
          disable-resp-body: true
      - path: /demo/json
        methods: POST
        log:
          log-req-header: Content-Type,Content-Length
          log-resp-header: Content-Type
      - path: /open/sign-demo
        methods: POST
        log:
          log-req-header: X-App-Id,X-Nonce,X-Timestamp,X-Signature
          log-resp-header: X-Nonce,X-Timestamp,X-Signature
      - path: /user/sign-in
        methods: POST
        sensitization:
          - logger: org.example.springbootdemo.support.HttpReqLogger
            sensitization-fields:
                # 匹配: fullName
              - patten: (fullName)("\s*:\s*"|=)([\u4e00-\u9fa5]{1})([\u4e00-\u9fa5]*)
                replace: $1$2$3**
              - patten: (phoneNo)("\s*:\s*"|=)(\d{3})\d{4}(\d{4})
                replace: $1$2$3****$4
              - patten: (idNo)("\s*:\s*"|=)(\d{6})\d{8,11}(\w{1})
                replace: $1$2$3**************$4
              - patten: (password)("\s*:\s*"|=).*?(?=("|,|&))
                replace: $1$2******
              - patten: (bankCardNo)("\s*:\s*"|=)(\d{4})\d{5,11}(\w{4})
                replace: $1$2$3**************$4
          - logger: org.example.springbootdemo.controller.UserController
            sensitization-fields:
              - patten: (fullName)("\s*:\s*"|=)([\u4e00-\u9fa5]{1})([\u4e00-\u9fa5]*)
                replace: $1$2$3**
              - patten: (phoneNo)("\s*:\s*"|=)(\d{3})\d{4}(\d{4})
                replace: $1$2$3****$4
              - patten: (idNo)("\s*:\s*"|=)(\d{6})\d{8,11}(\w{1})
                replace: $1$2$3**************$4
              - patten: (password)("\s*:\s*"|=).*?(?=("|,|&))
                replace: $1$2******
              - patten: (bankCardNo)("\s*:\s*"|=)(\d{4})\d{5,11}(\w{4})
                replace: $1$2$3**************$4
  rsa:
    private-key-path: classpath:key/rsa_private_key.pem
    public-key-path: classpath:key/rsa_public_key.pem

  sign:
    client-key:
      "app_id_001":
        key-path: classpath:sign/client/client_rsa_key.pem
    server-key:
      key-path: classpath:sign/server/server.pfx
      key-password: 123456
      cer-path: classpath:sign/client/server.cer
  jwt:
    private-key-path: classpath:jwt/rsa_private_key.pem
    public-key-path: classpath:jwt/rsa_public_key.pem

db:
  encrypt:
    aes-key: hsnl5n8r6zd8rt76tok05vmpun6y4nkc
